# Generated by Django 5.2 on 2025-04-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_reservation_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="confirmation_number",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="guest", name="gender", field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="guest", name="name", field=models.CharField(max_length=255),
        ),
    ]
