# Generated by Django 5.2 on 2025-04-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_reservation_confirmation_number_alter_guest_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="reservation",
            name="name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
